Repository linebender/druid, pull requests merged in 2020-10, with the labels that each got.

#1267 Store placeholder text as a separate TextLayout
  druid/examples/hello.rs
  druid/src/widget/textbox.rs
Labels: S-needs-review

#1287 Use widget::prelude::* where appropriate
  druid/examples/custom_widget.rs
  druid/src/scroll_component.rs
  druid/src/widget/align.rs
  druid/src/widget/button.rs
  druid/src/widget/checkbox.rs
  druid/src/widget/container.rs
  druid/src/widget/controller.rs
  druid/src/widget/either.rs
  druid/src/widget/env_scope.rs
  druid/src/widget/flex.rs
  druid/src/widget/identity_wrapper.rs
  druid/src/widget/image.rs
  druid/src/widget/label.rs
  druid/src/widget/padding.rs
  druid/src/widget/painter.rs
  druid/src/widget/parse.rs
  druid/src/widget/progress_bar.rs
  druid/src/widget/radio.rs
  druid/src/widget/scope.rs
  druid/src/widget/scroll.rs
  druid/src/widget/sized_box.rs
  druid/src/widget/slider.rs
  druid/src/widget/split.rs
  druid/src/widget/stepper.rs
  druid/src/widget/svg.rs
  druid/src/widget/switch.rs
  druid/src/widget/tabs.rs
  druid/src/widget/textbox.rs
  druid/src/widget/view_switcher.rs
  druid/src/window.rs
Labels: S-needs-review

#1280 Implement vertical movement (for text editing)
  CHANGELOG.md
  druid/src/text/editor.rs
  druid/src/text/layout.rs
  druid/src/text/movement.rs
  druid/src/text/selection.rs
  druid/src/text/text_input.rs
Labels: S-needs-review

#1282 Only draw selection when focused
  druid/src/widget/textbox.rs
Labels: S-needs-review

#1275 Centralize the WinHandler borrowing in gtk/x11 backends
  druid-shell/src/platform/gtk/window.rs
  druid-shell/src/platform/x11/application.rs
  druid-shell/src/platform/x11/window.rs
Labels: S-ready

#1285 Respect double-click rectangle
  druid-shell/src/platform/windows/window.rs
Labels: S-ready, shell/win

#1295 Expose baseline on TextLayout, add Baseline alignment to Flex
  CHANGELOG.md
  druid/examples/flex.rs
  druid/src/contexts.rs
  druid/src/core.rs
  druid/src/text/layout.rs
  druid/src/widget/button.rs
  druid/src/widget/checkbox.rs
  druid/src/widget/flex.rs
  druid/src/widget/label.rs
  druid/src/widget/slider.rs
  druid/src/widget/switch.rs
  druid/src/widget/textbox.rs
Labels: S-needs-review

#1315 Fix incorrect cursor position when hscroll > 0.0
  druid/src/widget/textbox.rs
Labels: S-needs-review

#1316 Allow access to Editor from TextBox
  druid/src/text/editor.rs
  druid/src/widget/textbox.rs
Labels: S-needs-review

#1314 Remove unused cairo-rs dependency from macOS
  druid-shell/Cargo.toml
Labels: S-needs-review

#1302 Make open/save dialogs no longer synchronous (in GTK)
  druid-shell/src/lib.rs
  druid-shell/src/platform/gtk/window.rs
  druid-shell/src/platform/mac/window.rs
  druid-shell/src/platform/web/window.rs
  druid-shell/src/platform/windows/window.rs
  druid-shell/src/platform/x11/window.rs
  druid-shell/src/window.rs
  druid/src/win_handler.rs
Labels: S-ready

#1321 Fix small bug in TextBox hscroll calculation
  druid/src/widget/textbox.rs
Labels: S-needs-review

#1320 Add TextBox::with_text_color & set_text_color
  CHANGELOG.md
  druid/src/widget/textbox.rs
Labels: S-needs-review

#1327 Make FontDescriptor construction const
  druid/src/text/font_descriptor.rs
Labels: S-needs-review

#1319 Remove minimum height from TextBox
  druid/src/widget/textbox.rs
Labels: S-ready

#1326 Add EventViewer example
  CHANGELOG.md
  druid/examples/event_viewer.rs
Labels: S-ready

#1325 Only account for baseline in Flex if needed
  druid/src/widget/flex.rs
Labels: S-waiting-on-author

#1283 Improve selection behaviour on focus change
  CHANGELOG.md
  druid/src/text/editor.rs
  druid/src/text/selection.rs
  druid/src/widget/textbox.rs
Labels: S-waiting-on-author

#1310 Display hotkeys for menu items in Windows
  CHANGELOG.md
  druid-shell/src/platform/windows/menu.rs
  druid/src/menu.rs
Labels: S-ready

#1272 Reduce flashing on window creation
  CHANGELOG.md
  druid-shell/src/platform/windows/window.rs
  druid-shell/src/window.rs
  druid/src/app.rs
Labels: S-ready

#1339 Make platform-specific menus more portable
  druid/src/menu.rs
Labels: S-needs-review

#1328 Make dialogs on windows non-sychronous.
  CHANGELOG.md
  druid-shell/examples/shello.rs
  druid-shell/src/platform/gtk/window.rs
  druid-shell/src/platform/mac/window.rs
  druid-shell/src/platform/web/window.rs
  druid-shell/src/platform/windows/application.rs
  druid-shell/src/platform/windows/window.rs
  druid-shell/src/platform/x11/window.rs
  druid-shell/src/window.rs
  druid/src/win_handler.rs
Labels: S-needs-review
