Repository linebender/druid, pull requests merged in 2020-11, with the labels that each got.

#1361 Allow setting the cursor in the update method.
  CHANGELOG.md
  druid/src/contexts.rs
  druid/src/core.rs
  druid/src/window.rs
Labels: S-ready

#1348 Rework cursor
  druid/examples/cursor.rs
Labels: S-needs-review

#1372 (slightly) rework either
  druid/examples/either.rs
  druid/resources/i18n/en-US/builtin.ftl
Labels: S-waiting-on-author

#1395 Do layout *just* before painting.
  druid/src/window.rs
Labels: S-ready

#1396 Implement Data for the NonZero integer types
  druid/src/data.rs
Labels: S-ready

#1392 Add Scroll::scroll_to and ClipBox::pan_to_visible
  druid/src/scroll_component.rs
  druid/src/widget/clip_box.rs
  druid/src/widget/scroll.rs
Labels: S-needs-review

#1393 Add axis and spacing to list.
  druid/examples/list.rs
  druid/src/widget/flex.rs
  druid/src/widget/list.rs
Labels: S-ready

#1397 Remove type param from Unit lens
  druid/src/lens/lens.rs
Labels: S-needs-review

#913 Add the resolution independence book chapter.
  CHANGELOG.md
  docs/src/SUMMARY.md
  docs/src/resolution_independence.md
Labels: S-ready, docs

#1091 Floor the origin for the Align widget
  CHANGELOG.md
  druid/src/widget/align.rs
Labels: S-ready

#1289 Add WidgetPod::set_origin, soft-deprecate set_layout_rect
  druid/src/core.rs
  druid/src/event.rs
  druid/src/widget/widget.rs
Labels: S-ready

#1371 Support text alignment in single-line TextBox
  CHANGELOG.md
  druid/src/text/mod.rs
  druid/src/widget/textbox.rs
Labels: S-needs-review

#1403 Request multiline textbox layout on update
  druid/src/text/editor.rs
Labels: S-ready

#1394 Notification sketch
  druid/src/command.rs
  druid/src/contexts.rs
  druid/src/core.rs
  druid/src/event.rs
  druid/src/lib.rs
  druid/src/tests/mod.rs
  druid/src/window.rs
Labels: S-ready

#1359 Defer context menus on gtk and windows.
  druid-shell/src/platform/gtk/window.rs
  druid-shell/src/platform/windows/window.rs
  druid-shell/src/window.rs
Labels: S-ready

#1407 Improve docs for Event and LifeCycle enums
  druid/src/event.rs
Labels: S-needs-review

#1420 Fix crochet helper method.
  druid/src/core.rs
Labels: S-needs-review

#1438 Add default minimum size to `WindowConfig`
  CHANGELOG.md
  druid/src/app.rs
Labels: S-waiting-on-author
