Repository linebender/druid, pull requests merged in 2020-09, with the labels that each got.

#1173 Remove fancy lifetime stuff from Env
  CHANGELOG.md
  druid/examples/styled_text.rs
  druid/src/data.rs
  druid/src/env.rs
  druid/src/lib.rs
  druid/src/theme.rs
  druid/src/widget/label.rs
  druid/src/widget/switch.rs
  druid/src/widget/textbox.rs
Labels: breaking change

#1107 Scroll behavior component
  AUTHORS
  CHANGELOG.md
  druid/src/lib.rs
  druid/src/scroll_component.rs
  druid/src/widget/scroll.rs
Labels: S-needs-review, architecture, widget

#1082 Constrain aspect ratio
  druid/src/box_constraints.rs
Labels: S-waiting-on-author

#1092 added EditAction::SelectNone
  CHANGELOG.md
  druid/src/text/editable_text.rs
  druid/src/text/movement.rs
  druid/src/text/text_input.rs
Labels: S-waiting-on-author

#1066 Restrict on_click() to left clicks only.
  druid/src/widget/click.rs
  druid/src/widget/widget_ext.rs
Labels: S-waiting-on-author

#1155 Move AnimFrame from lifecycle to event.
  CHANGELOG.md
  druid/examples/anim.rs
  druid/examples/invalidation.rs
  druid/src/core.rs
  druid/src/event.rs
  druid/src/scroll_component.rs
  druid/src/widget/spinner.rs
  druid/src/widget/switch.rs
  druid/src/win_handler.rs
  druid/src/window.rs
Labels: S-ready

#1209 Fix placeholder not showing in TextBox
  druid/src/widget/textbox.rs
Labels: S-ready

#1208 Fix the invalidation region for Scroll.
  druid/src/widget/scroll.rs
Labels: S-ready

#1214 Implements Data trait for i128 and u128
  CHANGELOG.md
  druid/src/data.rs
Labels: enhancement

#1211 Fix issues with placeholder TextBox text
  druid/examples/styled_text.rs
  druid/src/text/layout.rs
  druid/src/widget/textbox.rs
Labels: S-ready

#1195 Expose word wrap in TextLayout and Label
  CHANGELOG.md
  druid/examples/text.rs
  druid/examples/web/src/lib.rs
  druid/src/text/layout.rs
  druid/src/widget/label.rs
  druid/src/widget/mod.rs
Labels: S-needs-review

#1210 Add TextAlignment support to TextLayout and Label
  CHANGELOG.md
  druid/examples/text.rs
  druid/src/data.rs
  druid/src/lib.rs
  druid/src/text/layout.rs
  druid/src/widget/label.rs
Labels: S-needs-review

#1191 Use a simpler approach to Direct2D presentation
  CHANGELOG.md
  druid-shell/src/platform/windows/dcomp.rs
  druid-shell/src/platform/windows/mod.rs
  druid-shell/src/platform/windows/paint.rs
  druid-shell/src/platform/windows/util.rs
  druid-shell/src/platform/windows/window.rs
Labels: S-ready, shell/win

#1215 Use Global target for external events
  druid/src/command.rs
  druid/src/contexts.rs
  druid/src/ext_event.rs
  druid/src/tests/harness.rs
Labels: S-needs-review

#1225 Remove old deprecations
  druid/src/app.rs
  druid/src/contexts.rs
  druid/src/core.rs
Labels: S-ready

#1224 Mac and GTK implementation of Screen module and related window methods
  druid-shell/Cargo.toml
  druid-shell/src/platform/gtk/screen.rs
  druid-shell/src/platform/gtk/window.rs
  druid-shell/src/platform/mac/screen.rs
  druid-shell/src/platform/mac/window.rs
  druid-shell/src/screen.rs
  druid-shell/src/window.rs
Labels: S-needs-review

#1226 Add `Button::from_label`
  CHANGELOG.md
  druid/src/widget/button.rs
Labels: S-needs-review, enhancement, widget

#1227 Add tests to ensure that invalidation regions are transformed by scroll.
  druid/src/tests/harness.rs
  druid/src/tests/invalidation_tests.rs
  druid/src/tests/mod.rs
  druid/src/window.rs
Labels: S-needs-review

#1233 Adds a viewport widget.
  CHANGELOG.md
  druid/src/scroll_component.rs
  druid/src/widget/mod.rs
  druid/src/widget/scroll.rs
  druid/src/widget/viewport.rs
Labels: S-conflict

#1230 Set default label line break mode to Overflow to avoid Clip perf overhead
  druid/src/widget/label.rs
Labels: S-needs-review

#1220 Add default horizontal & vertical padding to theme
  CHANGELOG.md
  druid/examples/flex.rs
  druid/examples/identity.rs
  druid/examples/lens.rs
  druid/examples/parse.rs
  druid/examples/styled_text.rs
  druid/src/theme.rs
  druid/src/widget/flex.rs
Labels: S-conflict

#1238 Implement request_close() support for Windows in druid-shell
  CHANGELOG.md
  druid-shell/src/platform/windows/window.rs
Labels: S-waiting-on-author

#1237 Create default env with Env::default()
  druid/src/app.rs
  druid/src/core.rs
  druid/src/env.rs
  druid/src/tests/harness.rs
  druid/src/theme.rs
Labels: S-waiting-on-author

#1229 Fix bug with textbox placeholder selectable
  druid/src/widget/textbox.rs
Labels: S-ready

#1244 Set wrap width before rebuilding label
  druid/src/widget/label.rs
Labels: S-needs-review

#1241 Make GTK dependency optional.
  CHANGELOG.md
  druid-shell/Cargo.toml
  druid-shell/src/lib.rs
  druid/Cargo.toml
Labels: S-needs-review

#1235 Split up WindowDesc to allow sub-windows and window reconfiguration.
  CHANGELOG.md
  druid/src/app.rs
  druid/src/command.rs
  druid/src/lib.rs
  druid/src/tests/harness.rs
  druid/src/win_handler.rs
  druid/src/window.rs
Labels: S-ready

#1245 Use ArcStr in LocalizedString and LabelText
  CHANGELOG.md
  druid/src/localization.rs
  druid/src/menu.rs
  druid/src/widget/label.rs
  druid/src/win_handler.rs
  druid/src/window.rs
Labels: S-needs-review

#1252 Separate Label and RawLabel
  CHANGELOG.md
  druid/src/widget/label.rs
  druid/src/widget/mod.rs
Labels: S-ready

#1257 Add more file dialog configuration and macOS support (take 2)
  CHANGELOG.md
  druid-shell/src/dialog.rs
  druid-shell/src/platform/mac/dialog.rs
  druid/examples/open_save.rs
  druid/src/command.rs
Labels: S-ready, breaking change

#1160 Tabs widget and the Rotated widget that it uses.
  CHANGELOG.md
  druid/Cargo.toml
  druid/examples/tabs.rs
  druid/examples/web/src/lib.rs
  druid/src/lens/mod.rs
  druid/src/lib.rs
  druid/src/widget/flex.rs
  druid/src/widget/mod.rs
  druid/src/widget/tabs.rs
Labels: S-needs-review

#1255 Basic rich text
  CHANGELOG.md
  druid/examples/custom_widget.rs
  druid/examples/text.rs
  druid/src/core.rs
  druid/src/data.rs
  druid/src/lib.rs
  druid/src/text/attribute.rs
  druid/src/text/layout.rs
  druid/src/text/mod.rs
  druid/src/text/storage.rs
  druid/src/widget/label.rs
  druid/src/widget/switch.rs
  druid/src/widget/textbox.rs
Labels: S-needs-review
