Repository linebender/druid, pull requests merged in 2020-03, with the labels that each got.

#667 remove unwanted phantom data field from image
  druid/src/widget/image.rs
  druid/src/widget/svg.rs
Labels: S-waiting-on-author

#717 Fixups for new flex changes
  druid/examples/flex.rs
  druid/src/widget/radio.rs
Labels: S-needs-review

#733 Move root crate re-export docs to the root.
  druid/src/app_delegate.rs
  druid/src/box_constraints.rs
  druid/src/contexts.rs
  druid/src/core.rs
  druid/src/env.rs
  druid/src/event.rs
  druid/src/lens/lens.rs
  druid/src/lens/mod.rs
  druid/src/lib.rs
  druid/src/widget/click.rs
  druid/src/widget/controller.rs
  druid/src/widget/flex.rs
  druid/src/widget/mod.rs
  druid/src/widget/painter.rs
  druid/src/widget/widget.rs
  druid/src/widget/widget_ext.rs
Labels: S-needs-review

#752 Reimplement Button using on_click
  README.md
  druid/examples/flex.rs
  druid/examples/game_of_life.rs
  druid/examples/identity.rs
  druid/examples/layout.rs
  druid/examples/list.rs
  druid/examples/multiwin.rs
  druid/examples/view_switcher.rs
  druid/src/tests/mod.rs
  druid/src/widget/button.rs
Labels: S-needs-review

#767 Call update on system commands
  druid/src/win_handler.rs
Labels: bug

#760 Align Flex layout to integers.
  druid/src/box_constraints.rs
  druid/src/widget/flex.rs
Labels: S-needs-review

#772 Turn off event compression for gtk.
  druid-shell/src/platform/gtk/window.rs
Labels: S-needs-review

#775 Use glib::idle_add instead of rolling our own.
  druid-shell/src/platform/gtk/window.rs
Labels: S-needs-review

#709 Redirect vertical scrolling as horizontal scrolling when holding shift
  druid-shell/src/platform/gtk/window.rs
  druid-shell/src/platform/windows/window.rs
Labels: S-needs-review
