Repository linebender/druid, pull requests merged in 2020-08, with the labels that each got.

#1102 Give menu entries with "shift" shortcuts upper-case letters.
  druid/src/menu.rs
Labels: S-needs-review

#1112 ViewSwitcher uses Data instead of PartialEq
  CHANGELOG.md
  druid/src/widget/view_switcher.rs
Labels: breaking change

#1113 Skip update in ViewSwitcher after switching.
  CHANGELOG.md
  druid/src/widget/view_switcher.rs
Labels: S-needs-review, bug

#1120 Allow derivation of lenses for generic types.
  CHANGELOG.md
  druid-derive/src/lens.rs
  druid-derive/tests/lens_generic.rs
Labels: S-needs-review

#1126 Added BoxConstraints::UNBOUNDED
  CHANGELOG.md
  druid/src/box_constraints.rs
Labels: S-waiting-on-author

#1010 Add a widget gallery example.
  druid/Cargo.toml
  druid/examples/assets/xi.image
  druid/examples/web/src/lib.rs
  druid/examples/widget_gallery.rs
Labels: S-waiting-on-author, examples

#1145 Fix switch widget toggle animation being window refresh rate dependent
  CHANGELOG.md
  druid/src/widget/switch.rs
Labels: bug, widget

#1057 Revisit the druid <-> druid-shell animation and invalidation interface.
  CHANGELOG.md
  druid-shell/examples/invalidate.rs
  druid-shell/examples/perftest.rs
  druid-shell/examples/quit.rs
  druid-shell/examples/shello.rs
  druid-shell/src/lib.rs
  druid-shell/src/platform/gtk/window.rs
  druid-shell/src/platform/mac/window.rs
  druid-shell/src/platform/web/window.rs
  druid-shell/src/platform/windows/util.rs
  druid-shell/src/platform/windows/window.rs
  druid-shell/src/platform/x11/window.rs
  druid-shell/src/region.rs
  druid-shell/src/window.rs
  druid/Cargo.toml
  druid/examples/anim.rs
  druid/examples/invalidation.rs
  druid/src/contexts.rs
  druid/src/core.rs
  druid/src/lib.rs
  druid/src/tests/harness.rs
  druid/src/tests/helpers.rs
  druid/src/widget/invalidation.rs
  druid/src/widget/scroll.rs
  druid/src/widget/spinner.rs
  druid/src/widget/switch.rs
  druid/src/win_handler.rs
  druid/src/window.rs
Labels: S-needs-review

#1157 Multi-click mouse events on Windows
  CHANGELOG.md
  druid-shell/src/platform/windows/window.rs
Labels: S-needs-review, shell/win
