Repository linebender/druid, pull requests merged in 2020-04, with the labels that each got.

#782 Reduce the flashing in ext_event and identity examples
  druid/examples/ext_event.rs
  druid/examples/identity.rs
Labels: S-needs-review

#808 Replace `#[macro_use]` with normal `use`
  druid-shell/src/keyboard.rs
  druid-shell/src/lib.rs
  druid-shell/src/platform/gtk/clipboard.rs
  druid-shell/src/platform/gtk/dialog.rs
  druid-shell/src/platform/mac/application.rs
  druid-shell/src/platform/mac/clipboard.rs
  druid-shell/src/platform/mac/dialog.rs
  druid-shell/src/platform/mac/menu.rs
  druid-shell/src/platform/mac/util.rs
  druid-shell/src/platform/mac/window.rs
  druid-shell/src/platform/windows/accels.rs
  druid-shell/src/platform/windows/dcomp.rs
  druid-shell/src/platform/windows/dialog.rs
  druid-shell/src/platform/windows/error.rs
  druid-shell/src/platform/windows/timers.rs
  druid-shell/src/platform/windows/util.rs
  druid-shell/src/platform/x11/application.rs
Labels: S-needs-review

#812 Update X11 CI checkout to v2.
  .github/workflows/ci.yml
Labels: S-needs-review

#738 Improve Split accuracy.
  druid/examples/split_demo.rs
  druid/examples/view_switcher.rs
  druid/src/core.rs
  druid/src/tests/layout_tests.rs
  druid/src/tests/mod.rs
  druid/src/widget/split.rs
Labels: S-needs-review

#816 Make the text module public
  druid/src/lib.rs
  druid/src/text/text_input.rs
Labels: S-needs-review

#611 Remove use GTK optional feature
  druid-shell/Cargo.toml
  druid-shell/src/application.rs
  druid-shell/src/clipboard.rs
  druid-shell/src/platform/mod.rs
  druid/Cargo.toml
  druid/src/win_handler.rs
Labels: S-needs-review

#830 Log if no WidgetPod::set_layout_rect before event
  druid/src/core.rs
  druid/src/tests/layout_tests.rs
Labels: S-needs-review

#821 Add Event::MouseLeave for windows
  druid-shell/src/platform/windows/window.rs
  druid-shell/src/window.rs
  druid/src/core.rs
  druid/src/event.rs
  druid/src/win_handler.rs
Labels: S-waiting-on-author

#833 Move internal events to a separate enum.
  druid/src/core.rs
  druid/src/event.rs
  druid/src/lib.rs
  druid/src/tests/harness.rs
  druid/src/tests/helpers.rs
  druid/src/tests/mod.rs
  druid/src/widget/scroll.rs
  druid/src/win_handler.rs
  druid/src/window.rs
Labels: breaking change

#837 Ignore nested events in GTK shell
  druid-shell/src/platform/gtk/window.rs
Labels: S-needs-review

#841 Keep hot state consistent with mouse position.
  druid/examples/timer.rs
  druid/src/contexts.rs
  druid/src/core.rs
  druid/src/tests/harness.rs
  druid/src/widget/align.rs
  druid/src/widget/checkbox.rs
  druid/src/widget/container.rs
  druid/src/widget/either.rs
  druid/src/widget/flex.rs
  druid/src/widget/list.rs
  druid/src/widget/padding.rs
  druid/src/widget/radio.rs
  druid/src/widget/scroll.rs
  druid/src/widget/split.rs
  druid/src/widget/view_switcher.rs
  druid/src/win_handler.rs
  druid/src/window.rs
Labels: breaking change, bug

#847 Change request_timer to work with Duration
  docs/book_examples/src/custom_widgets_md.rs
  druid-shell/examples/shello.rs
  druid-shell/src/window.rs
  druid/examples/game_of_life.rs
  druid/examples/identity.rs
  druid/examples/timer.rs
  druid/src/contexts.rs
  druid/src/widget/scroll.rs
  druid/src/widget/stepper.rs
  druid/src/widget/textbox.rs
Labels: breaking change

#845 Add hot glow option to multiwin example.
  druid/examples/multiwin.rs
Labels: S-needs-review, examples

#850 Add clippy checks for examples and tests.
  .github/workflows/ci.yml
  Cargo.lock
  druid-derive/Cargo.toml
  druid-derive/tests/with_lens.rs
  druid-derive/tests/with_same.rs
  druid/Cargo.toml
  druid/examples/ext_event.rs
  druid/examples/timer.rs
  druid/src/core.rs
  druid/src/localization.rs
  druid/src/tests/helpers.rs
  druid/src/tests/layout_tests.rs
  druid/src/tests/mod.rs
  druid/src/text/editable_text.rs
  druid/src/widget/flex.rs
Labels: S-needs-review

#856 Remove unnecessary WidgetPod from multiwin's Glow widget.
  druid/examples/multiwin.rs
Labels: S-needs-review, examples

#858 Fix wasm examples not building on Windows with a standard user.
  druid/examples/wasm/build.rs
Labels: S-needs-review

#763 Terminate app run loop on Windows when all windows have closed.
  druid-shell/examples/invalidate.rs
  druid-shell/examples/perftest.rs
  druid-shell/examples/shello.rs
  druid-shell/src/application.rs
  druid-shell/src/clipboard.rs
  druid-shell/src/error.rs
  druid-shell/src/lib.rs
  druid-shell/src/platform/gtk/application.rs
  druid-shell/src/platform/gtk/window.rs
  druid-shell/src/platform/mac/application.rs
  druid-shell/src/platform/mac/util.rs
  druid-shell/src/platform/mac/window.rs
  druid-shell/src/platform/web/application.rs
  druid-shell/src/platform/web/window.rs
  druid-shell/src/platform/windows/application.rs
  druid-shell/src/platform/windows/util.rs
  druid-shell/src/platform/windows/window.rs
  druid-shell/src/platform/x11/application.rs
  druid-shell/src/platform/x11/window.rs
  druid-shell/src/util.rs
  druid-shell/src/window.rs
  druid/src/app.rs
  druid/src/command.rs
  druid/src/widget/textbox.rs
  druid/src/win_handler.rs
Labels: S-needs-review, breaking change

#831 Associate timers with widget ids
  druid/src/contexts.rs
  druid/src/core.rs
  druid/src/event.rs
  druid/src/window.rs
Labels: S-waiting-on-author

#785 Add option to set label fonts
  druid/examples/styled_text.rs
  druid/src/widget/label.rs
Labels: S-waiting-on-author

#877 Add temporary workaround for flickering on Windows.
  druid-shell/src/platform/windows/window.rs
Labels: S-needs-review, shell/win

#840 Add new example for blocking functions
  druid/examples/blocking_function.rs
  druid/examples/wasm/build.rs
Labels: S-waiting-on-author

#889 Add a Changelog
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
Labels: S-needs-review

#843 Add support for more mouse buttons and tracking holding.
  CHANGELOG.md
  druid-shell/src/lib.rs
  druid-shell/src/mouse.rs
  druid-shell/src/platform/gtk/window.rs
  druid-shell/src/platform/mac/window.rs
  druid-shell/src/platform/web/window.rs
  druid-shell/src/platform/windows/window.rs
  druid-shell/src/platform/x11/application.rs
  druid-shell/src/platform/x11/window.rs
  druid/src/lib.rs
  druid/src/mouse.rs
  druid/src/tests/mod.rs
Labels: S-needs-review, breaking change
