Repository linebender/druid, pull requests merged in 2021-07, with the labels that each got.

#1843 LinuxApplicationExt: experiment with platforms specific extensions
  CHANGELOG.md
  druid-shell/src/backend/gtk/application.rs
  druid-shell/src/backend/gtk/clipboard.rs
  druid-shell/src/clipboard.rs
  druid-shell/src/lib.rs
  druid-shell/src/platform/linux.rs
  druid-shell/src/platform/mod.rs
Labels: S-needs-review

#1850 Added font support for SVG text
  CHANGELOG.md
  druid/src/widget/svg.rs
Labels: S-waiting-on-author

#1856 Placeholder text respects alignment
  druid/src/text/input_component.rs
  druid/src/widget/textbox.rs
Labels: S-ready
