Repository linebender/druid, pull requests merged in 2021-05, with the labels that each got.

#1737 Implement tooltip level on Windows platform
  CHANGELOG.md
  druid-shell/src/platform/windows/window.rs
Labels: S-waiting-on-author

#1751 X11 Scaling
  CHANGELOG.md
  druid-shell/Cargo.toml
  druid-shell/src/platform/x11/application.rs
  druid-shell/src/platform/x11/window.rs
Labels: shell/x11

#1746 druid-shell: Added Delete key handling
  CHANGELOG.md
  druid-shell/src/text.rs
Labels: S-ready, shell

#1755 X11 cursors
  CHANGELOG.md
  druid-shell/Cargo.toml
  druid-shell/src/platform/x11/application.rs
  druid-shell/src/platform/x11/window.rs
Labels: shell/x11

#1756 X11 shell locale detection
  CHANGELOG.md
  druid-shell/src/platform/x11/application.rs
Labels: S-ready, shell/x11

#1759 `quit` example: Use the unused `file_menu`
  druid-shell/examples/quit.rs
Labels: S-needs-review

#1761 updating docs to use Selector.with instead of Command::new
  CHANGELOG.md
  druid/examples/open_save.rs
  druid/src/command.rs
  druid/src/core.rs
  druid/src/sub_window.rs
  druid/src/tests/mod.rs
Labels: S-needs-review

#1772 Update fluent
  CHANGELOG.md
  druid/Cargo.toml
  druid/src/localization.rs
Labels: S-ready

#1750 Update README.md example to match version 0.7.0
  README.md
Labels: S-ready

#1775 Correctly clip the TextBox
  druid/src/widget/textbox.rs
Labels: S-ready

#1645 Aspect ratio box
  CHANGELOG.md
  druid/examples/layout.rs
  druid/src/tests/layout_tests.rs
  druid/src/widget/aspect_ratio_box.rs
  druid/src/widget/mod.rs
Labels: S-ready

#1780 Fix typos in Clipboard docs
  druid-shell/src/clipboard.rs
Labels: S-needs-review, docs

#1784 Convert some state from RefCell to Cell in x11 backend
  druid-shell/src/platform/x11/window.rs
Labels: shell/x11

#1776 Use point/size in ClipBox instead of rect.
  druid/src/scroll_component.rs
  druid/src/widget/clip_box.rs
  druid/src/widget/scroll.rs
Labels: S-ready

#1791 [web backend] Implement Application::locale
  druid-shell/Cargo.toml
  druid-shell/src/platform/web/application.rs
Labels: S-ready

#1790 [web backend] Make sure we only request animation once per frame
  druid-shell/src/platform/web/window.rs
Labels: S-ready

#1793 [web backend] Limit max level log to debug and update tracing-wasm
  druid/Cargo.toml
  druid/src/app.rs
Labels: S-ready

#1786 Improve `simulate_input`
  druid-shell/src/text.rs
Labels: S-ready

#1796 [ci] Install libxkbcommon for #1779
  .github/workflows/ci.yml
Labels: S-ready

#1802 druid: update usvg
  CHANGELOG.md
  druid/Cargo.toml
Labels: S-ready

#1792 [web backend] Handle keydown events correctly
  druid-shell/src/platform/web/window.rs
Labels: S-needs-review
