Repository linebender/druid, pull requests merged in 2021-01, with the labels that each got.

#1254 Sub windows (squashed from previous branch)
  CHANGELOG.md
  druid-shell/Cargo.toml
  druid-shell/src/platform/mac/window.rs
  druid/examples/sub_window.rs
  druid/examples/web/build.rs
  druid/src/command.rs
  druid/src/contexts.rs
  druid/src/core.rs
  druid/src/event.rs
  druid/src/lib.rs
  druid/src/sub_window.rs
  druid/src/win_handler.rs
Labels: S-needs-review

#1447 change Image example
  druid/examples/image.rs
  druid/src/data.rs
  druid/src/widget/common.rs
Labels: S-waiting-on-author

#1446 small changes in hello example
  druid/examples/hello.rs
Labels: S-waiting-on-author

#1443 cleanup game of life
  druid/examples/game_of_life.rs
Labels: S-waiting-on-author

#1533 Warn on Unhandled commands
  CHANGELOG.md
  druid/src/command.rs
  druid/src/win_handler.rs
Labels: discussion
