Repository linebender/druid, pull requests merged in 2021-04, with the labels that each got.

#1700 Allow restarting Application
  druid-shell/src/application.rs
  druid-shell/src/platform/windows/application.rs
Labels: S-needs-review

#1632 Disable widgets
  CHANGELOG.md
  druid/src/contexts.rs
  druid/src/core.rs
  druid/src/event.rs
  druid/src/tests/harness.rs
  druid/src/tests/mod.rs
  druid/src/widget/textbox.rs
  druid/src/window.rs
Labels: S-waiting-on-author

#1695 GTK Shell: Manually get/set textual data in clipboard
  CHANGELOG.md
  druid-shell/src/platform/gtk/clipboard.rs
Labels: S-needs-review, shell/gtk

#1696 Add missing derived lens documentation
  CHANGELOG.md
  druid-derive/src/lens.rs
Labels: S-needs-review

#1715 Improve layout of the scrollbar
  CHANGELOG.md
  druid/src/scroll_component.rs
  druid/src/widget/flex.rs
  druid/src/widget/scroll.rs
Labels: S-needs-review

#1724 Focus-chain update
  CHANGELOG.md
  druid/src/core.rs
  druid/src/event.rs
Labels: S-needs-review

#1732 Book: Fix the intro tutorial
  docs/src/get_started.md
  docs/src/setup.md
Labels: S-ready

#1726 Lock split cursor state when active
  druid/src/widget/split.rs
Labels: S-waiting-on-author

#1730 Fix link in documentation of widget::Image
  CHANGELOG.md
  druid/src/widget/image.rs
Labels: S-needs-review

#1744 Provide access to lens in LensWrap
  druid/src/widget/lens_wrap.rs
Labels: S-needs-review

#1722 [GTK] Implement content_insets for GTK.
  CHANGELOG.md
  druid-shell/src/platform/gtk/window.rs
  druid-shell/src/window.rs
Labels: S-needs-review

#1743 Implement Data for chrono types
  CHANGELOG.md
  druid/Cargo.toml
  druid/src/data.rs
Labels: S-ready

#1733 Test out Swatinem's cache.
  .github/workflows/ci.yml
Labels: S-ready
