Repository linebender/druid, pull requests merged in 2023-02, with the labels that each got.

#2346 Foreground function for Container Widget and WidgetExt
  CHANGELOG.md
  druid/src/widget/container.rs
  druid/src/widget/widget_ext.rs
Labels: widget

#2349 Add info about symbolic links to `CONTRIBUTING.md`.
  CHANGELOG.md
  CONTRIBUTING.md
  druid/README.md
Labels: maintenance

#2353 Fix `rustdoc` example scraping configuration.
  .github/workflows/ci.yml
  CHANGELOG.md
  druid-shell/Cargo.toml
  druid/Cargo.toml
Labels: maintenance

#2356 Fix doc visibility issues.
  CHANGELOG.md
  druid-shell/src/mouse.rs
  druid-shell/src/region.rs
  druid/src/app.rs
  druid/src/lens/mod.rs
  druid/src/lib.rs
  druid/src/theme.rs
  druid/src/widget/mod.rs
  druid/src/widget/parse.rs
  druid/src/widget/widget_ext.rs
Labels: docs

#2191 Show/Hide Window Programmatically
  CHANGELOG.md
  druid-shell/src/backend/gtk/window.rs
  druid-shell/src/backend/mac/window.rs
  druid-shell/src/backend/wayland/window.rs
  druid-shell/src/backend/web/window.rs
  druid-shell/src/backend/windows/window.rs
  druid-shell/src/backend/x11/window.rs
  druid-shell/src/window.rs
  druid/src/command.rs
  druid/src/win_handler.rs
Labels: shell

#2328 Input Region and Always On Top support
  AUTHORS
  CHANGELOG.md
  druid-shell/src/backend/gtk/window.rs
  druid-shell/src/backend/mac/window.rs
  druid-shell/src/backend/wayland/application.rs
  druid-shell/src/backend/wayland/surfaces/layershell.rs
  druid-shell/src/backend/wayland/surfaces/mod.rs
  druid-shell/src/backend/wayland/surfaces/popup.rs
  druid-shell/src/backend/wayland/surfaces/surface.rs
  druid-shell/src/backend/wayland/window.rs
  druid-shell/src/backend/web/window.rs
  druid-shell/src/backend/windows/window.rs
  druid-shell/src/backend/x11/window.rs
  druid-shell/src/region.rs
  druid-shell/src/window.rs
  druid/examples/input_region.rs
  druid/examples/readme.md
  druid/examples/web/build.rs
  druid/src/app.rs
Labels: shell, port-to-glazier

#2363 Satisfy clippy 1.68 beta.
  druid-shell/src/backend/windows/window.rs
  druid/src/scroll_component.rs
  druid/src/widget/common.rs
Labels: maintenance, S-needs-review

#2364 Update dependencies to latest semver compatible versions.
  druid-derive/Cargo.toml
  druid-shell/Cargo.toml
  druid/Cargo.toml
  druid/examples/hello_web/Cargo.toml
  druid/examples/web/Cargo.toml
Labels: maintenance, S-needs-review

#2365 Prepare for releasing v0.8.3.
  CHANGELOG.md
  README.md
  docs/src/08_widgets_in_depth.md
  druid-derive/Cargo.toml
  druid-shell/Cargo.toml
  druid/Cargo.toml
  druid/src/lib.rs
  druid/src/widget/flex.rs
Labels: maintenance, S-needs-review
