Repository linebender/druid, pull requests merged in 2023-01, with the labels that each got.

#2320 Remove outdated documentation in LifeCycle events
  CHANGELOG.md
  druid/src/event.rs
Labels: docs

#2322 Add missing copyright headers.
  druid-derive/tests/data.rs
  druid-derive/tests/ignore.rs
  druid-derive/tests/lens_generic.rs
  druid-derive/tests/ui.rs
  druid-derive/tests/with_lens.rs
  druid-derive/tests/with_same.rs
  druid-shell/build.rs
  druid-shell/src/backend/shared/linux/env.rs
  druid-shell/src/backend/shared/linux/mod.rs
  druid-shell/src/backend/shared/timer.rs
  druid-shell/src/backend/shared/xkb/keycodes.rs
  druid-shell/src/backend/shared/xkb/xkbcommon_sys.rs
  druid-shell/src/backend/wayland/display.rs
  druid-shell/src/backend/wayland/events.rs
  druid-shell/src/backend/wayland/keyboard.rs
  druid-shell/src/backend/wayland/outputs/mod.rs
  druid-shell/src/backend/wayland/outputs/output.rs
  druid-shell/src/backend/wayland/pointers.rs
  druid-shell/src/backend/wayland/surfaces/buffers.rs
  druid-shell/src/backend/wayland/surfaces/idle.rs
  druid-shell/src/backend/wayland/surfaces/layershell.rs
  druid-shell/src/backend/wayland/surfaces/mod.rs
  druid-shell/src/backend/wayland/surfaces/popup.rs
  druid-shell/src/backend/wayland/surfaces/surface.rs
  druid-shell/src/backend/wayland/surfaces/toplevel.rs
  druid-shell/src/backend/wayland/window.rs
  druid-shell/src/backend/x11/dialog.rs
  druid-shell/src/region.rs
  druid/examples/sub_window.rs
  druid/examples/switches.rs
  druid/examples/tabs.rs
  druid/examples/widget_gallery.rs
  druid/src/debug_state.rs
  druid/src/widget/intrinsic_width.rs
  druid/src/widget/scope.rs
  druid/src/widget/widget_wrapper.rs
  druid/src/widget/z_stack.rs
Labels: maintenance, S-needs-review, port-to-glazier

#2324 Properly handle mouse leave event on GTK
  CHANGELOG.md
  druid-shell/src/backend/gtk/window.rs
Labels: shell/gtk, port-to-glazier

#2323 Update AnimFrame docs with info about when paint happens.
  CHANGELOG.md
  druid-shell/src/screen.rs
  druid/src/contexts.rs
  druid/src/event.rs
  druid/src/widget/widget_wrapper.rs
Labels: docs

#2325 Fix rustdoc warnings
  druid-shell/src/screen.rs
  druid/src/widget/svg.rs
Labels: maintenance

#2319 Add a public constructor to StringCursor
  CHANGELOG.md
  druid/src/text/editable_text.rs
Labels: S-waiting-on-author

#2301 Various documentation-related fixes
  CONTRIBUTING.md
  README.md
  docs/book_examples/Cargo.toml
  docs/book_examples/src/getting_started_2_md.rs
  docs/book_examples/src/getting_started_md.rs
  docs/book_examples/src/lib.rs
  docs/src/01_overview.md
  docs/src/02_getting_started.md
  docs/src/03_data.md
  docs/src/04_widget.md
  docs/src/05_lens.md
  docs/src/06_env.md
  docs/src/07_resolution_independence.md
  docs/src/08_widgets_in_depth.md
  docs/src/09_more_information.md
  docs/src/SUMMARY.md
  docs/src/command.md
  docs/src/data.md
  docs/src/get_started.md
  docs/src/localization.md
  docs/src/setup.md
  druid-shell/src/backend/windows/mod.rs
  druid-shell/src/backend/windows/window.rs
  druid/Cargo.toml
  druid/examples/cursor.rs
  druid/examples/event_viewer.rs
  druid/examples/game_of_life.rs
  druid/examples/identity.rs
  druid/examples/layout.rs
  druid/examples/readme.md
  druid/examples/value_formatting/src/widgets.rs
  druid/src/app.rs
  druid/src/command.rs
  druid/src/contexts.rs
  druid/src/core.rs
  druid/src/data.rs
  druid/src/event.rs
  druid/src/lib.rs
  druid/src/tests/harness.rs
  druid/src/text/format.rs
  druid/src/widget/clip_box.rs
  druid/src/widget/common.rs
  druid/src/widget/flex.rs
  druid/src/widget/slider.rs
  druid/src/widget/split.rs
  druid/src/widget/stepper.rs
  druid/src/widget/svg.rs
  druid/src/widget/z_stack.rs
  druid/src/win_handler.rs
Labels: docs

#2327 Update Rust edition to 2021.
  docs/book_examples/Cargo.toml
  druid-shell/Cargo.toml
  druid-shell/src/backend/web/window.rs
  druid/Cargo.toml
  druid/examples/hello_web/Cargo.toml
  druid/examples/value_formatting/Cargo.toml
  druid/examples/web/Cargo.toml
Labels: maintenance, S-needs-review

#2330 Update repository documentation
  CONTRIBUTING.md
  README.md
  docs/src/01_overview.md
Labels: docs, port-to-glazier

#2335 Add `Event::WindowScale` and `Ctx::scale` for easier scale handling.
  CHANGELOG.md
  druid-shell/src/window.rs
  druid/src/contexts.rs
  druid/src/core.rs
  druid/src/event.rs
  druid/src/lib.rs
  druid/src/widget/svg.rs
  druid/src/win_handler.rs
Labels: widget, architecture

#2340 Remove `set_layout_rect` and fix deprecation declarations.
  CHANGELOG.md
  druid-shell/src/mouse.rs
  druid/examples/styled_text.rs
  druid/examples/switches.rs
  druid/src/app.rs
  druid/src/core.rs
  druid/src/menu/mod.rs
  druid/src/widget/mod.rs
  druid/src/widget/parse.rs
  druid/src/widget/widget_ext.rs
Labels: maintenance

#2341 Fix miscellaneous documentation.
  README.md
  druid-shell/README.md
  druid-shell/src/backend/x11/window.rs
  druid-shell/src/hotkey.rs
  druid/examples/image.rs
  druid/src/contexts.rs
  druid/src/lib.rs
  druid/src/widget/clip_box.rs
  druid/src/widget/textbox.rs
Labels: docs

#2343 Fix `ScrollComponent` not handling `LifeCycle::HotChanged`.
  CHANGELOG.md
  druid/src/event.rs
  druid/src/scroll_component.rs
Labels: widget

#2338 Fix documentation links.
  CHANGELOG.md
  druid-shell/src/clipboard.rs
  druid-shell/src/dialog.rs
  druid-shell/src/menu.rs
  druid-shell/src/mouse.rs
  druid/src/app.rs
  druid/src/app_delegate.rs
  druid/src/box_constraints.rs
  druid/src/command.rs
  druid/src/contexts.rs
  druid/src/core.rs
  druid/src/data.rs
  druid/src/env.rs
  druid/src/event.rs
  druid/src/ext_event.rs
  druid/src/lens/lens.rs
  druid/src/lib.rs
  druid/src/localization.rs
  druid/src/mouse.rs
  druid/src/tests/harness.rs
  druid/src/text/attribute.rs
  druid/src/text/font_descriptor.rs
  druid/src/text/format.rs
  druid/src/text/layout.rs
  druid/src/text/rich_text.rs
  druid/src/text/storage.rs
  druid/src/widget/button.rs
  druid/src/widget/click.rs
  druid/src/widget/clip_box.rs
  druid/src/widget/container.rs
  druid/src/widget/controller.rs
  druid/src/widget/env_scope.rs
  druid/src/widget/flex.rs
  druid/src/widget/image.rs
  druid/src/widget/label.rs
  druid/src/widget/lens_wrap.rs
  druid/src/widget/mod.rs
  druid/src/widget/painter.rs
  druid/src/widget/spinner.rs
  druid/src/widget/svg.rs
  druid/src/widget/textbox.rs
  druid/src/widget/value_textbox.rs
  druid/src/widget/widget.rs
  druid/src/widget/widget_ext.rs
Labels: docs

#2345 Update Piet to v0.6.1.
  druid-derive/Cargo.toml
  druid-shell/Cargo.toml
  druid/Cargo.toml
  druid/src/widget/svg.rs
Labels: maintenance

#2337 Use standardized Druid naming convention.
  CHANGELOG.md
  docs/src/02_getting_started.md
  docs/src/05_lens.md
  docs/src/07_resolution_independence.md
  druid-derive/Cargo.toml
  druid-derive/README.md
  druid-derive/src/lib.rs
  druid-shell/Cargo.toml
  druid-shell/examples/edit_text.rs
  druid-shell/src/backend/mac/mod.rs
  druid-shell/src/backend/mac/window.rs
  druid-shell/src/backend/wayland/error.rs
  druid-shell/src/backend/wayland/keyboard.rs
  druid-shell/src/backend/windows/mod.rs
  druid-shell/src/backend/windows/window.rs
  druid-shell/src/backend/x11/mod.rs
  druid-shell/src/lib.rs
  druid-shell/src/scale.rs
  druid-shell/src/text.rs
  druid/examples/game_of_life.rs
  druid/examples/hello.rs
  druid/examples/hello_web/README.md
  druid/examples/layout.rs
  druid/examples/readme.md
  druid/examples/styled_text.rs
  druid/examples/value_formatting/README.md
  druid/examples/web/Cargo.toml
  druid/src/app.rs
  druid/src/box_constraints.rs
  druid/src/command.rs
  druid/src/core.rs
  druid/src/data.rs
  druid/src/dialog.rs
  druid/src/env.rs
  druid/src/event.rs
  druid/src/lib.rs
  druid/src/menu/mod.rs
  druid/src/tests/harness.rs
  druid/src/text/input_methods.rs
  druid/src/text/storage.rs
  druid/src/widget/align.rs
  druid/src/widget/image.rs
  druid/src/widget/lens_wrap.rs
  druid/src/widget/value_textbox.rs
  druid/src/win_handler.rs
Labels: docs

#2342 Rewrite changelog in preparation for releasing v0.8.0
  CHANGELOG.md
Labels: docs, S-needs-review

#2336 Increase crate versions in preparation for releasing v0.8.0
  README.md
  docs/src/08_widgets_in_depth.md
  druid-derive/Cargo.toml
  druid-shell/Cargo.toml
  druid/Cargo.toml
  druid/src/lib.rs
Labels: maintenance

#2347 Fix crates.io `README.md` selection and prep v0.8.1.
  CHANGELOG.md
  README.md
  docs/src/08_widgets_in_depth.md
  druid-derive/Cargo.toml
  druid/Cargo.toml
  druid/src/lib.rs
  druid/src/widget/flex.rs
Labels: maintenance

#2348 Fix docs.rs building and docs.rs `README.md` displaying.
  CHANGELOG.md
  README.md
  docs/src/08_widgets_in_depth.md
  druid-derive/Cargo.toml
  druid/Cargo.toml
  druid/README.md
  druid/src/lib.rs
  druid/src/widget/flex.rs
Labels: maintenance

#2352 Synchronize `kurbo` and `image` imports with `piet-common`.
  CHANGELOG.md
  druid-shell/Cargo.toml
  druid-shell/src/backend/gtk/screen.rs
  druid-shell/src/backend/mac/screen.rs
  druid-shell/src/backend/wayland/screen.rs
  druid-shell/src/backend/wayland/surfaces/buffers.rs
  druid-shell/src/lib.rs
  druid-shell/src/region.rs
  druid/Cargo.toml
Labels: maintenance
